### PR TITLE
refactor(edgeorder): migrate to unified folder structure

### PR DESCRIPTION
**Pull request by qiaozha**
This PR migrates the EdgeOrder specification to the new unified folder structure according to Azure folder structure guidelines.

**Changes:**
- Consolidated TypeSpec and Swagger files under resource-manager/Microsoft.EdgeOrder/EdgeOrder/
- Updated tspconfig.yaml with correct paths and ARM types directory
- Fixed all common-types references and input-file paths in readme.md
- Added suppressions.yaml for legacy API versions
- Verified TypeSpec compilation works correctly

**Benefits:**
- Unified structure for better maintainability
- Aligns with Azure folder structure standards
- Maintains backward compatibility
- Supports future TypeSpec migration efforts

### CODE REVIEW

**Review by lirenhe — APPROVED** [review]

**Comment by live1206** [comment]
The .NET SDK validation failure is due to naming standards, which could be fixed with `@clientName`
```
/mnt/vss/_work/1/s/azure-sdk-for-net/sdk/edgeorder/Azure.ResourceManager.EdgeOrder/src/Generated/Models/AddressUpdateParameter.cs(14,26): error AZC0030: Model name 'AddressUpdateParameter' ends with 'Parameter'. Suggest to rename it to 'AddressUpdateContent' or 'AddressUpdatePatch' or any other appropriate name. [/mnt/vss/_work/1/s/azure-sdk-for-net/sdk/edgeorder/Azure.ResourceManager.EdgeOrder/src/Azure.ResourceManager.EdgeOrder.csproj::TargetFramework=netstandard2.0]
```
Details can be found in https://dev.azure.com/azure-sdk/public/_build/results?buildId=5151692&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=583

**Comment by ArcturusZhang** [comment]
@raych1 why the pipelines for go and python both reported "has breaking change", but we see no labels for that on this PR?

**Comment by qiaozha** [comment]
@raych1 can you help investigate the question that @ArcturusZhang and @tadelesh found? The breaking change is introduced in https://github.com/Azure/azure-rest-api-specs/pull/34238 this PR but there's no SDK breaking change suppression file for it. Which we should expect SDK breaking change label for Go and Python, but no such label is tagged.

**Comment by raych1** [comment]
> @raych1 can you help investigate the question that @ArcturusZhang and @tadelesh found? The breaking change is introduced in #34238 this PR but there's no SDK breaking change suppression file for it. Which we should expect SDK breaking change label for Go and Python, but no such label is tagged.

@qiaozha you are right. It's not supported for V2 folder structure. This is the [issue](https://github.com/Azure/azure-sdk-tools/issues/11539) created to track the work.
